[build]
command = "remix build"
functions = "netlify/functions"
publish = "public"

[dev]
command = "remix watch"
port = 3000

[[redirects]]
from = "/*"
status = 200
to = "/.netlify/functions/server"

[[headers]]
for = "/build/*"
[headers.values]
"Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
